spring:
  application:
    name: dating_app
  datasource:
    url: jdbc:mysql://localhost:3306/dating_app?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    jwt:
      secret-key: mif66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbi
      expiration: 604800000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.hbm2ddl: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


server:
  port: 8080

firebase:
  config:
    path:
      privateKey: "scripts/fcm/firebase-pvt-key.json"


